version: '3.2'
services:
  web_client:
    image: strimpack-web-client:master
    volumes:
      - 'client_assets:/usr/src/strimpack-web-client/'
  site:
    image: strimpack:master
    depends_on:
      - 'postgresql'
      - 'web_client'
    volumes:
      - 'client_assets:/usr/src/strimpack-web-client/'
    ports:
      - '8080:8080'
    env_file:
      - '.env.docker'
  chat:
    image: strimchat:master
    depends_on:
      - 'postgresql'
    ports:
      - '8082:8082'
    env_file:
      - '.env.docker'
  discourse:
    image: 'bitnami/discourse:latest'
    ports:
      - '80:3000'
    volumes:
      - 'discourse_data:/strimpack'
    depends_on:
      - 'postgresql'
      - 'redis'
      - 'site' # role creation happens in site script
    env_file:
      - '.env.docker'
  sidekiq:
    image: 'bitnami/discourse:latest'
    depends_on:
      - discourse
    volumes:
      - 'sidekiq_data:/strimpack'
    command: 'nami start --foreground discourse-sidekiq'
    env_file:
      - '.env.docker'
  redis:
    image: 'redis:alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/strimpack'
  postgresql:
    image: 'sameersbn/postgresql:9.6-2'
    volumes:
      - 'postgresql_data:/strimpack'
    environment:
      - DB_USER
      - DB_PASS
      - DB_NAME
      - PG_PASSWORD
  # lb:
  #   image: rancher/lb-service-haproxy
  #   ports:
  #   - 80:80/tcp
volumes:
  client_assets:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  discourse_data:
    driver: local
  sidekiq_data:
    driver: local
